name: 2nd Cup
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25098
title: All the inspiration you want as you start your 2nd cup in the morning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#134f8b'
    - '#4a7fb5'
    - '#ddd6c6'
    - '#71a4d4'
  brandStrength: 1
  lightness: 0.6386981678660959
  saturation: 0.7629269047174603
  rhythmicContrast: 0.2963063092902303
purpose: []
